### ISSUE TITLE
Recipes for slabs don't seem to work in 2020.4

### ISSUE THREAD

**Issue by navarayuk** [Pylo/MCreatorGenerator-Forge-1.12.2#10]
**Describe the bug**
Created a recipe for a slab in 2020.4 with the latest 1.12.2 Gen and when I create a recipe for a slab no matter what I do it does not seem to show up in game, no errors given when building, but if you use vanilla items as the item it creates the vanilla item, this also works with the basic block, this stopped soon as I tried the slabs

As a quick test I also tested Fence, that base seemed to work fine, soon as I put the base back to slab it stops working

From what I have been reading on how to fix this I came across a code by yourself it seems that it's still missing 

`"data": 0,`

When your creating the recipe file for slabs in this generator.

**Works**
![image](https://user-images.githubusercontent.com/70470100/91656833-eded0300-eab3-11ea-95c9-759e270a56f1.png)

**Don't work**
![image](https://user-images.githubusercontent.com/70470100/91656846-09580e00-eab4-11ea-9701-b03e2da71b44.png)

**Game Log Error**
<details>
<summary>Show Text</summary>
<p>

## _Code_ 

11:06.06 [main/ERROR] [FML]: Parsing error loading recipe ccex:coarse_dirt_slab_recipe 
com.google.gson.JsonParseException: Missing data for item 'ccex:coarse_dirt_slab' 
   at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:215) ~[CraftingHelper.class:?] 
   at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:516) ~[CraftingHelper.class:?] 
   at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?] 
   at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?] 
   at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?] 
   at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?] 
   at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_252] 
   at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?] 
   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?] 
   at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?] 
   at net.minecraft.client.Minecraft.init(Minecraft.java:581) [Minecraft.class:?] 
   at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?] 
   at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?] 
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] 
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] 
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] 
   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] 
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?] 
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] 
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] 
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] 
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] 
   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] 
   at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?] 
   at GradleStart.main(GradleStart.java:25) [start/:?]
</p></details>
**To Reproduce**
Simple create a block give it a recipe

**Screenshots**
![image](https://user-images.githubusercontent.com/70470100/91656361-11ae4a00-eab0-11ea-89fa-697721fe6731.png)
![image](https://user-images.githubusercontent.com/70470100/91656515-2b03c600-eab1-11ea-99db-6001f60bcd13.png)

**Details**
 - OS: Windows 10
 - MCreator version: 2020.4
 - Generator type: forge-1.12.2

**Comment by KlemenDEV** [comment]
This generator is unsupported, but I will try to look into it if I get some time.

**Comment by KlemenDEV** [comment]
Original: https://mcreator.net/tracker/issue/59779

**Comment by navarayuk** [comment]
That is the post I believe I found with the fix, and I don't mind the manual fix to is I know 1.12.2 isn't supported but still nice to still be able to make mods, I know you want people to update but even now no real modpack creator is wanting to move to 1.14+ this is how it is really for a few years when a old version is put to rest.

1.12.2 is still the most up to date modded stable version out there, 1.16 might change that but until forge and mods catch up right now 1.12.2 is where everything seems to be staying for now, so thanks for pushing this out.

**Comment by KlemenDEV** [comment]
I generally don't have time to work on issues here, thus open-source for others to take initiative, but I just got idea for a fix so I will look into it.
